"""initial_domain_models

Revision ID: 791f3845eefd
Revises: 
Create Date: 2026-07-23 16:18:17.268813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791f3845eefd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agency_memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('agency_admin', 'agency_member', 'client_user')", name='chk_agency_memberships_role'),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agency_id', name='uq_agency_memberships_user_agency')
    )
    op.create_index(op.f('ix_agency_memberships_agency_id'), 'agency_memberships', ['agency_id'], unique=False)
    op.create_index(op.f('ix_agency_memberships_user_id'), 'agency_memberships', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'name', name='uq_clients_agency_name'),
    sa.UniqueConstraint('id', 'agency_id', name='uq_clients_id_agency')
    )
    op.create_index(op.f('ix_clients_agency_id'), 'clients', ['agency_id'], unique=False)
    op.create_table('client_memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id', 'agency_id'], ['clients.id', 'clients.agency_id'], name='fk_client_memberships_client_agency', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agency_id', name='uq_client_memberships_user_agency'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_client_memberships_user_client')
    )
    op.create_index('ix_client_memberships_agency_user', 'client_memberships', ['agency_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_client_memberships_client_id'), 'client_memberships', ['client_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('agency_admin', 'agency_member', 'client_user')", name='chk_invitations_role'),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'expired', 'revoked')", name='chk_invitations_status'),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id', 'agency_id'], ['clients.id', 'clients.agency_id'], name='fk_invitations_client_agency', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_index('uq_pending_invitation', 'invitations', ['agency_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived', 'completed')", name='chk_projects_status'),
    sa.ForeignKeyConstraint(['client_id', 'agency_id'], ['clients.id', 'clients.agency_id'], name='fk_projects_client_agency', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'client_id', 'name', name='uq_projects_agency_client_name'),
    sa.UniqueConstraint('id', 'agency_id', name='uq_projects_id_agency')
    )
    op.create_index(op.f('ix_projects_agency_id'), 'projects', ['agency_id'], unique=False)
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_table('project_memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'agency_id'], ['projects.id', 'projects.agency_id'], name='fk_project_memberships_project_agency', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_project_memberships_user_project')
    )
    op.create_index('ix_project_memberships_agency_project', 'project_memberships', ['agency_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_project_memberships_user_id'), 'project_memberships', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'todo'"), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('visibility', sa.String(length=10), server_default=sa.text("'internal'"), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent')", name='chk_tasks_priority'),
    sa.CheckConstraint("status IN ('todo', 'in_progress', 'review', 'done')", name='chk_tasks_status'),
    sa.CheckConstraint("visibility IN ('internal', 'client')", name='chk_tasks_visibility'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id', 'agency_id'], ['projects.id', 'projects.agency_id'], name='fk_tasks_project_agency', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'agency_id', name='uq_tasks_id_agency')
    )
    op.create_index(op.f('ix_tasks_agency_id'), 'tasks', ['agency_id'], unique=False)
    op.create_index('ix_tasks_agency_project_visibility', 'tasks', ['agency_id', 'project_id', 'visibility'], unique=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=10), server_default=sa.text("'internal'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('internal', 'client')", name='chk_comments_visibility'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id', 'agency_id'], ['tasks.id', 'tasks.agency_id'], name='fk_comments_task_agency', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_agency_id'), 'comments', ['agency_id'], unique=False)
    op.create_index('ix_comments_task_visibility', 'comments', ['task_id', 'visibility'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('visibility', sa.String(length=10), server_default=sa.text("'internal'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('internal', 'client')", name='chk_files_visibility'),
    sa.ForeignKeyConstraint(['task_id', 'agency_id'], ['tasks.id', 'tasks.agency_id'], name='fk_files_task_agency', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'agency_id', name='uq_files_id_agency')
    )
    op.create_index(op.f('ix_files_agency_id'), 'files', ['agency_id'], unique=False)
    op.create_index('ix_files_task_visibility', 'files', ['task_id', 'visibility'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='chk_time_entries_duration'),
    sa.ForeignKeyConstraint(['project_id', 'agency_id'], ['projects.id', 'projects.agency_id'], name='fk_time_entries_project_agency'),
    sa.ForeignKeyConstraint(['task_id', 'agency_id'], ['tasks.id', 'tasks.agency_id'], name='fk_time_entries_task_agency', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_entries_agency_project', 'time_entries', ['agency_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_time_entries_task_id'), 'time_entries', ['task_id'], unique=False)
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    op.create_table('file_approvals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id', 'agency_id'], ['files.id', 'files.agency_id'], name='fk_file_approvals_file_agency', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'reviewer_id', name='uq_file_approvals_file_reviewer')
    )
    op.create_index(op.f('ix_file_approvals_agency_id'), 'file_approvals', ['agency_id'], unique=False)
    op.create_index(op.f('ix_file_approvals_file_id'), 'file_approvals', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_approvals_file_id'), table_name='file_approvals')
    op.drop_index(op.f('ix_file_approvals_agency_id'), table_name='file_approvals')
    op.drop_table('file_approvals')
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_task_id'), table_name='time_entries')
    op.drop_index('ix_time_entries_agency_project', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index('ix_files_task_visibility', table_name='files')
    op.drop_index(op.f('ix_files_agency_id'), table_name='files')
    op.drop_table('files')
    op.drop_index('ix_comments_task_visibility', table_name='comments')
    op.drop_index(op.f('ix_comments_agency_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_index('ix_tasks_agency_project_visibility', table_name='tasks')
    op.drop_index(op.f('ix_tasks_agency_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_project_memberships_user_id'), table_name='project_memberships')
    op.drop_index('ix_project_memberships_agency_project', table_name='project_memberships')
    op.drop_table('project_memberships')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_agency_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('uq_pending_invitation', table_name='invitations', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_client_memberships_client_id'), table_name='client_memberships')
    op.drop_index('ix_client_memberships_agency_user', table_name='client_memberships')
    op.drop_table('client_memberships')
    op.drop_index(op.f('ix_clients_agency_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_agency_memberships_user_id'), table_name='agency_memberships')
    op.drop_index(op.f('ix_agency_memberships_agency_id'), table_name='agency_memberships')
    op.drop_table('agency_memberships')
    op.drop_table('users')
    op.drop_table('agencies')
    # ### end Alembic commands ###
